apiVersion: v1
kind: Pod
metadata:
  name: non-persistent-redis
  namespace: pre-prod
spec:
  containers:
  - image: redis
    name: redis
    volumeMounts:
    - mountPath: /data/reids
      name: cache-control
  volumes:
  - name: cache-control
    emptyDir: {}
