apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    app: nginx-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.11.9-alpine

# this file should be used with --record in terminal
# to update the image: kubectl set image deployment nginx-app nginx=nginx:1.12.0-alpine --record
# to rollback to previous version: kubectl rollout undo deployment nginx-app